// Code generated by hertz generator.

package user

import (
	"Gomall/app/api/middleware"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...

	return nil
}

func _logoutMw() []app.HandlerFunc {
	middlewares := make([]app.HandlerFunc, 0)
	middlewares = append(middlewares, middleware.Auth())
	return middlewares
}

func _deleteuserMw() []app.HandlerFunc {
	middlewares := make([]app.HandlerFunc, 0)
	middlewares = append(middlewares, middleware.Auth())
	return middlewares
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}
