// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	category "Gomall/app/api/biz/router/category"
	product "Gomall/app/api/biz/router/product"
	user "Gomall/app/api/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	category.Register(r)

	product.Register(r)

	user.Register(r)
}