// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	cart "Gomall/app/api/biz/router/cart"
	category "Gomall/app/api/biz/router/category"
	order "Gomall/app/api/biz/router/order"
	payment "Gomall/app/api/biz/router/payment"
	product "Gomall/app/api/biz/router/product"
	user "Gomall/app/api/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	payment.Register(r)

	cart.Register(r)

	order.Register(r)

	category.Register(r)

	product.Register(r)

	user.Register(r)
}
